# PBS configuration

# If submitting to a different project to your default, uncomment line below 
# and change project code as appropriate; also set shortpath below
# project: x77

# Force payu to always find, and save, files in this scratch project directory
# (you may need to add the corresponding PBS -l storage flag in sync_data.sh)
# shortpath: /scratch/v45

queue: normalsr
ncpus: 1976
jobfs: 10GB
mem: 9500GB


walltime: 10:00:00
jobname: Ningaloo

model: access-om3

exe: access-om3-MOM6
input:
    - /g/data/vk83/configurations/inputs/access-om3/share/meshes/share/2024.09.16/JRA55do-datm-ESMFmesh.nc
    - /g/data/vk83/configurations/inputs/access-om3/share/meshes/share/2024.09.16/JRA55do-drof-ESMFmesh.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/Ningaloo_domain/hgrid.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/Ningaloo_domain/vcoord.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/Ningaloo_domain/bathymetry_mod.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/Ningaloo_domain/init_tracers_modified.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/Ningaloo_domain/obgc_obc.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/Ningaloo_domain/init_eta.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/Ningaloo_domain/init_vel.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/Ningaloo_domain/grid_spec.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/Ningaloo_domain/ocean_mosaic.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/Ningaloo_domain/access-rom3-ESMFmesh.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/Ningaloo_domain/access-rom3-nomask-ESMFmesh.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/Ningaloo_domain/dust_DS.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/Ningaloo_domain/tz_segment_001.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/Ningaloo_domain/tz_segment_002.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/Ningaloo_domain/tz_segment_003.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/Ningaloo_domain/tz_segment_004.nc    
    - /scratch/nm03/ee8016/regional_mom6_configs/Ningaloo_domain/tu_segment_001.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/Ningaloo_domain/tu_segment_002.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/Ningaloo_domain/tu_segment_003.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/Ningaloo_domain/tu_segment_004.nc
    - /g/data/qv56/replicas/input4MIPs/CMIP6Plus/OMIP/MRI/MRI-JRA55-do-1-6-0/
collate: false
runlog: false
metadata: 
    enable: false

platform:
    nodesize: 104
    nodemem: 512

# userscripts:
#     setup: /usr/bin/bash /g/data/vk83/apps/om3-scripts/payu_config/setup.sh
#     archive: /usr/bin/bash /g/data/vk83/apps/om3-scripts/payu_config/archive.sh

modules:
    use:
        - /g/data/vk83/prerelease/modules
    load:
        - access-om3/pr144-1
        - nco/5.0.5
        
env:
payu_minimum_version: 1.1.6
